easy_admin:
    site_name: Setlistify
    entities:
        # List the entity class name you want to manage
        Song:
            class: App\Entity\Song
        Setlist:
            class: App\Entity\Setlist
        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - name
                    - lastname                    
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

